// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDleooV2KEyJKSYVuhqkXmoT_06aS2HbkA',
    appId: '1:926236916835:web:5e91291fec1e9bb0b6cc56',
    messagingSenderId: '926236916835',
    projectId: 'task-app-4d84a',
    authDomain: 'task-app-4d84a.firebaseapp.com',
    storageBucket: 'task-app-4d84a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxrdrKVItCOts77E7vXM8-EHMIukwce4s',
    appId: '1:926236916835:android:b983219e540ecc2eb6cc56',
    messagingSenderId: '926236916835',
    projectId: 'task-app-4d84a',
    storageBucket: 'task-app-4d84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBevqBVezl88wXntasYQrWlf1b4RLB-9ao',
    appId: '1:926236916835:ios:f27f5d98b4f80281b6cc56',
    messagingSenderId: '926236916835',
    projectId: 'task-app-4d84a',
    storageBucket: 'task-app-4d84a.firebasestorage.app',
    iosBundleId: 'com.example.taskApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBevqBVezl88wXntasYQrWlf1b4RLB-9ao',
    appId: '1:926236916835:ios:f27f5d98b4f80281b6cc56',
    messagingSenderId: '926236916835',
    projectId: 'task-app-4d84a',
    storageBucket: 'task-app-4d84a.firebasestorage.app',
    iosBundleId: 'com.example.taskApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDleooV2KEyJKSYVuhqkXmoT_06aS2HbkA',
    appId: '1:926236916835:web:75c82659a7d0c4a1b6cc56',
    messagingSenderId: '926236916835',
    projectId: 'task-app-4d84a',
    authDomain: 'task-app-4d84a.firebaseapp.com',
    storageBucket: 'task-app-4d84a.firebasestorage.app',
  );
}
