name: task_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
